package azure

import (
	"fmt"
	"regexp"
	"strings"
)

type BicepPlan struct {
	ControlIDs []string `json:"controlIds"`
	Risk       string   `json:"risk"`
	CostImpact string   `json:"costImpact"`
	Source     string   `json:"source"`
}

var azureName = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.()-]{0,88}[A-Za-z0-9)]$`)

func GenerateBicepPlan(target Target) (BicepPlan, error) {
	if !azureName.MatchString(target.WorkspaceName) || !azureName.MatchString(target.ResourceGroup) {
		return BicepPlan{}, fmt.Errorf("resource group or workspace name contains unsupported characters")
	}
	retention := target.MinimumRetentionDays
	if retention == 0 {
		retention = 90
	}
	if retention < 30 || retention > 730 {
		return BicepPlan{}, fmt.Errorf("retention must be between 30 and 730 days")
	}
	source := fmt.Sprintf(`// Generated by TriSOC Attestor. Review before deployment; no credentials are embedded.
// Controls: microsoft.sentinel.enabled, microsoft.sentinel.workspace_retention
targetScope = 'resourceGroup'

param workspaceName string = '%s'
param workspaceLocation string = resourceGroup().location
param minimumRetentionDays int = %d

resource workspace 'Microsoft.OperationalInsights/workspaces@2025-07-01' existing = {
  name: workspaceName
}

resource workspaceRetention 'Microsoft.OperationalInsights/workspaces@2025-07-01' = {
  name: workspace.name
  location: workspaceLocation
  properties: {
    retentionInDays: minimumRetentionDays
  }
}

resource sentinel 'Microsoft.SecurityInsights/onboardingStates@2024-09-01' = {
  scope: workspace
  name: 'default'
  properties: {
    customerManagedKey: false
  }
}
`, strings.ReplaceAll(target.WorkspaceName, "'", "''"), retention)
	return BicepPlan{ControlIDs: []string{"microsoft.sentinel.enabled", "microsoft.sentinel.workspace_retention"}, Risk: "medium", CostImpact: "usage_dependent", Source: source}, nil
}
